**IRIS FSI PRACTICA2.PDF**

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

#load the iris dataset
iris = load_iris()

X = iris.data
encoder = LabelBinarizer()
y = encoder.fit_transform(iris.target)  # We transform to one-hot

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.15)

In [ ]:
import keras
from keras.layers import Input, Dense
from keras.models import Model
from keras.optimizers import SGD #Stochastic Gradient Descent Optimizer

inputs = Input(shape=(4,))  # We have four inputs
x = Dense(5, activation='sigmoid')(inputs)  # five neurons and sigmoid as activation function
predictions = Dense(3, activation='softmax')(x)  # Output layer with three neurons, one for each class

# This creates a model
model = Model(inputs=inputs, outputs=predictions)
sgd = SGD(lr=0.1)
model.compile(optimizer=sgd,
              loss='mse',  # Mean Squared Error
              metrics=['accuracy'])

print(model.summary())

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
dense_9 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_10 (Dense)             (None, 3)                 18        
Total params: 43
Trainable params: 43
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X_train, y_train, epochs=500)

Epoch 1/500
107/107 [==============================] - 0s 2ms/step - loss: 0.2175 - accuracy: 0.3084
Epoch 2/500
107/107 [==============================] - 0s 92us/step - loss: 0.2159 - accuracy: 0.3178
Epoch 3/500
107/107 [==============================] - 0s 86us/step - loss: 0.2144 - accuracy: 0.3551
Epoch 4/500
107/107 [==============================] - 0s 85us/step - loss: 0.2133 - accuracy: 0.4486
Epoch 5/500
107/107 [==============================] - 0s 81us/step - loss: 0.2121 - accuracy: 0.6262
Epoch 6/500
107/107 [==============================] - 0s 74us/step - loss: 0.2113 - accuracy: 0.6449
Epoch 7/500
107/107 [==============================] - 0s 64us/step - loss: 0.2104 - accuracy: 0.6449
Epoch 8/500
107/107 [==============================] - 0s 72us/step - loss: 0.2095 - accuracy: 0.6449
Epoch 9/500
107/107 [==============================] - 0s 67us/step - loss: 0.2084 - accuracy: 0.6449
Epoch 10/500
107/107 [==============================] - 0s 64us/step - loss: 0.2076

In [ ]:
predictions = model.predict(X_test)
for p, l in zip(np.round(predictions, 10), y_test):
  if np.argmax(p) == np.argmax(l):
        print(p, "->", l)
  else:
        print(p, "->", l, "✘")

[0.07760763 0.7075106  0.21488176] -> [0 1 0]
[0.9105759  0.08427052 0.00515358] -> [1 0 0]
[0.87460977 0.11834775 0.00704241] -> [1 0 0]
[0.06350171 0.67450845 0.26198986] -> [0 1 0]
[0.02169617 0.36423704 0.6140667 ] -> [0 0 1]
[0.10408903 0.6673058  0.22860515] -> [0 1 0]
[0.19278805 0.69049627 0.11671563] -> [0 1 0]
[0.06242036 0.6295598  0.30801985] -> [0 1 0]
[0.02542789 0.35856682 0.6160053 ] -> [0 0 1]
[0.03773517 0.4935189  0.46874595] -> [0 0 1] ✘
[0.8543204  0.1373719  0.00830775] -> [1 0 0]
[0.8763543  0.11667323 0.00697255] -> [1 0 0]
[0.03305472 0.47225097 0.49469423] -> [0 0 1]
[0.0164301  0.25763878 0.72593117] -> [0 0 1]
[0.8674352  0.12490692 0.0076579 ] -> [1 0 0]
[0.018608   0.30959105 0.671801  ] -> [0 0 1]
[0.01293278 0.24897175 0.7380954 ] -> [0 0 1]
[0.10114584 0.6874209  0.21143335] -> [0 1 0]
[0.01057133 0.21286587 0.77656275] -> [0 0 1]
[0.09489681 0.7173033  0.18779983] -> [0 1 0]
[0.01622459 0.27755138 0.706224  ] -> [0 0 1]
[0.04782841 0.59293973 0.3592317

**MNIST FSI PRACTICA2.PDF**

In [ ]:
from keras.datasets import mnist
import numpy as np
from sklearn.model_selection import train_test_split


batch_size = 128
num_classes = 10
epochs = 5

# the data, split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()
(X_train, y_train), (X_val, y_val) = mnist.load_data()

X_train = X_train.reshape(60000, 784)  # 28x28=784
X_test = X_test.reshape(10000, 784)
X_val = X_val.reshape(10000, 784)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_val = X_val.astype('float32')
X_train /= 255  # We normalize to have values between 0 and 1
X_test /= 255
X_val /= 255

#convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)  # onehot encoding
y_test = keras.utils.to_categorical(y_test, num_classes)
y_val = keras.utils.to_categorical(y_val, num_classes)

In [ ]:
import keras
from keras.layers import Input, Dense
from keras.models import Model
from keras.optimizers import SGD #Stochastic Gradient Descent Optimizer

inputs = Input(shape=(784,))  # We have 784 inputs
x = Dense(128, activation='sigmoid')(inputs)  # 128 neurons and sigmoid as activation function
predictions = Dense(num_classes, activation='softmax')(x)  # Output layer with three neurons, one for each class

# This creates a model
model = Model(inputs=inputs, outputs=predictions)
sgd = SGD(lr=0.1)
model.compile(optimizer=sgd,
              loss='mse',  # Mean Squared Error
              metrics=['accuracy'])

print(model.summary())

Model: "model_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        (None, 784)               0         
_________________________________________________________________
dense_26 (Dense)             (None, 128)               100480    
_________________________________________________________________
dense_27 (Dense)             (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X_train, y_train, epochs=100, batch_size=batch_size)  # starts training with epochs and batch_size gived

Epoch 1/120
60000/60000 [==============================] - 2s 25us/step - loss: 0.0893 - accuracy: 0.2328
Epoch 2/120
60000/60000 [==============================] - 1s 25us/step - loss: 0.0845 - accuracy: 0.3823
Epoch 3/120
60000/60000 [==============================] - 1s 25us/step - loss: 0.0799 - accuracy: 0.4755
Epoch 4/120
60000/60000 [==============================] - 1s 25us/step - loss: 0.0746 - accuracy: 0.5594
Epoch 5/120
60000/60000 [==============================] - 1s 25us/step - loss: 0.0687 - accuracy: 0.6117
Epoch 6/120
60000/60000 [==============================] - 1s 25us/step - loss: 0.0627 - accuracy: 0.6392
Epoch 7/120
60000/60000 [==============================] - 1s 24us/step - loss: 0.0571 - accuracy: 0.6711
Epoch 8/120
60000/60000 [==============================] - 1s 25us/step - loss: 0.0522 - accuracy: 0.7054
Epoch 9/120
60000/60000 [==============================] - 1s 25us/step - loss: 0.0479 - accuracy: 0.7340
Epoch 10/120
60000/60000 [====================

KeyboardInterrupt: ignored

In [ ]:
predictions = model.predict(X_test)
for p, l in zip(np.round(predictions, 10), y_test):
  if np.argmax(p) == np.argmax(l):
        print(p, "->", l)
  else:
        print(p, "->", l, "✘")

Se han truncado las últimas 5000 líneas del flujo de salida.
[0.05490896 0.01122622 0.5570778  0.05027731 0.00215328 0.0549361
 0.0231288  0.0015575  0.23934942 0.00538456] -> [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0.03372524 0.01560499 0.06956022 0.53995764 0.00966987 0.14922
 0.00483932 0.02131626 0.09432214 0.06178427] -> [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0.00254677 0.00330167 0.01132147 0.00167136 0.81558937 0.01668175
 0.01901457 0.01551159 0.01305397 0.10130759] -> [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0.01494427 0.07540015 0.20071581 0.03908815 0.19561596 0.12417299
 0.10999589 0.03522515 0.13329618 0.0715455 ] -> [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ✘
[0.00977053 0.01720491 0.23104542 0.00816736 0.03234268 0.02960436
 0.6422406  0.00168772 0.02069722 0.00723924] -> [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0.0068474  0.10863212 0.01483118 0.00977705 0.04943437 0.05351987
 0.00763093 0.55223745 0.12078888 0.07630081] -> [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0.28330705 0.00382446 0.04244404 0.07088996 0.015652