In [0]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

#load the iris dataset
iris = load_iris()

X = iris.data
encoder = LabelBinarizer()
y = encoder.fit_transform(iris.target)  # We transform to one-hot
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [0]:
import keras
from keras.layers import Input, Dense
from keras.models import Model
from keras.optimizers import SGD #Stochastic Gradient Descent Optimizer

inputs = Input(shape=(4,))  # We have four inputs
x = Dense(5, activation='sigmoid')(inputs)  # five neurons and sigmoid as activation function
predictions = Dense(3, activation='softmax')(x)  # Output layer with three neurons, one for each class

# This creates a model
model = Model(inputs=inputs, outputs=predictions)
sgd = SGD(lr=0.1)
model.compile(optimizer=sgd,
              loss='mse',  # Mean Squared Error
              metrics=['accuracy'])

print(model.summary())

Using TensorFlow backend.


Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 18        
Total params: 43
Trainable params: 43
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
model.fit(X_train, y_train, epochs=500)  # starts training with 500 epochs

Epoch 1/500
112/112 [==============================] - 0s 2ms/step - loss: 0.2065 - accuracy: 0.3750
Epoch 2/500
112/112 [==============================] - 0s 74us/step - loss: 0.2046 - accuracy: 0.4018
Epoch 3/500
112/112 [==============================] - 0s 70us/step - loss: 0.2028 - accuracy: 0.4018
Epoch 4/500
112/112 [==============================] - 0s 76us/step - loss: 0.2013 - accuracy: 0.4107
Epoch 5/500
112/112 [==============================] - 0s 77us/step - loss: 0.1999 - accuracy: 0.4375
Epoch 6/500
112/112 [==============================] - 0s 78us/step - loss: 0.1985 - accuracy: 0.4911
Epoch 7/500
112/112 [==============================] - 0s 75us/step - loss: 0.1972 - accuracy: 0.4911
Epoch 8/500
112/112 [==============================] - 0s 56us/step - loss: 0.1959 - accuracy: 0.5446
Epoch 9/500
112/112 [==============================] - 0s 61us/step - loss: 0.1946 - accuracy: 0.5357
Epoch 10/500
112/112 [==============================] - 0s 57us/step - loss: 0.1937

In [0]:
predictions = model.predict(X_test)
for p, l in zip(predictions, y_test):
    print(p,"->", l)

[0.02571145 0.35174876 0.6225398 ] -> [0 0 1]
[0.06994177 0.6941008  0.23595752] -> [0 1 0]
[0.910665   0.08577637 0.0035586 ] -> [1 0 0]
[0.8842829  0.11061766 0.00509947] -> [1 0 0]
[0.02966195 0.42353365 0.5468044 ] -> [0 0 1]
[0.12230898 0.71006054 0.16763055] -> [0 1 0]
[0.08404643 0.7084354  0.20751809] -> [0 1 0]
[0.08915897 0.700692   0.21014899] -> [0 1 0]
[0.02063476 0.28258482 0.69678044] -> [0 0 1]
[0.0320739  0.38855824 0.5793679 ] -> [0 0 1]
[0.81547654 0.17477347 0.00975004] -> [1 0 0]
[0.01715876 0.25612068 0.7267206 ] -> [0 0 1]
[0.01992447 0.29341596 0.6866596 ] -> [0 0 1]
[0.08467106 0.70495486 0.2103741 ] -> [0 1 0]
[0.8979618  0.09785106 0.00418718] -> [1 0 0]
[0.87691075 0.11759067 0.00549857] -> [1 0 0]
[0.02274587 0.30464834 0.6726057 ] -> [0 0 1]
[0.09542445 0.66665256 0.23792292] -> [0 1 0]
[0.88444084 0.11049486 0.00506431] -> [1 0 0]
[0.9330147  0.06466207 0.0023233 ] -> [1 0 0]
[0.03259441 0.40360007 0.5638055 ] -> [0 0 1]
[0.019678   0.30020452 0.6801175 ]

**Realización de la tarea**

In [0]:
from keras.datasets import mnist

batch_size = 128
num_classes = 10
epochs = 5

# the data, split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(60000, 784)  # 28x28=784
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255  # We normalize to have values between 0 and 1
X_test /= 255

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)  # onehot encoding
y_test = keras.utils.to_categorical(y_test, num_classes)

In [0]:
import keras
from keras.layers import Input, Dense
from keras.models import Model
from keras.optimizers import SGD #Stochastic Gradient Descent Optimizer

inputs = Input(shape=(784,))  # We have 784 inputs
x = Dense(128, activation='sigmoid')(inputs)  # 128 neurons and sigmoid as activation function
predictions = Dense(num_classes, activation='softmax')(x)  # Output layer with three neurons, one for each class

# This creates a model
model = Model(inputs=inputs, outputs=predictions)
sgd = SGD(lr=0.1)
model.compile(optimizer=sgd,
              loss='mse',  # Mean Squared Error
              metrics=['accuracy'])

print(model.summary())

Model: "model_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_17 (Dense)             (None, 128)               100480    
_________________________________________________________________
dense_18 (Dense)             (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)  # starts training with epochs and batch_size gived

Epoch 1/5
60000/60000 [==============================] - 2s 25us/step - loss: 0.0224 - accuracy: 0.8774
Epoch 2/5
60000/60000 [==============================] - 1s 25us/step - loss: 0.0219 - accuracy: 0.8788
Epoch 3/5
60000/60000 [==============================] - 1s 25us/step - loss: 0.0215 - accuracy: 0.8802
Epoch 4/5
60000/60000 [==============================] - 1s 24us/step - loss: 0.0211 - accuracy: 0.8820
Epoch 5/5
60000/60000 [==============================] - 1s 25us/step - loss: 0.0207 - accuracy: 0.8831


In [0]:
predictions = model.predict(X_test)
for p, l in zip(np.round(predictions, 10), y_test):
  if np.argmax(p) == np.argmax(l):
        print(p, "->", l)
  else:
        print(p, "->", l, "✘")

Se han truncado las últimas 5000 líneas del flujo de salida.
 3.2320444e-03 8.8724513e-03 8.6399389e-04 4.6179495e-03 9.3620336e-03] -> [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.3381716e-02 8.4156619e-04 1.9854998e-02 9.1901535e-01 1.1577560e-04
 4.0135540e-02 5.1154580e-04 4.9086899e-04 5.3325631e-03 3.2009641e-04] -> [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0.00346341 0.00386938 0.00316074 0.07335658 0.009993   0.08351969
 0.00212972 0.0116075  0.6919946  0.11690524] -> [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0.00902529 0.00554482 0.01231753 0.2610104  0.00535928 0.14890814
 0.00484414 0.00150873 0.53673023 0.01475154] -> [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[2.3250319e-03 5.1474059e-04 4.1253171e-03 9.7361386e-01 7.6795899e-05
 1.5211644e-02 1.3149150e-04 1.0562635e-03 2.3714907e-03 5.7326100e-04] -> [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[9.4843167e-01 2.9238900e-05 2.6632887e-03 7.9164578e-04 5.2845263e-04
 3.7352186e-02 7.8684483e-03 8.4387918e-04 6.5291702e-04 8.3828479e-04] -> [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2